#!/usr/bin/env python3
"""Build the first-stage first-person hand assets from the archived OBJ/PBR set.

The runtime deliberately stays small and dependency-free: each hand is an
independent, UV-aware indexed BufferGeometry payload embedded in classic
JavaScript, and the four source PBR images become three package-local WebP
textures.  The source archive is read-only and every generated byte is
deterministic so a rebuild can be checked by hash.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image


EXPECTED_OBJ_SHA256 = "3b4d53b98dfa965c64543ae6a9d351a04576cd2357dabebbe2be2fd08eaf8266"
TARGET_TOTAL_TRIANGLES = 18000
TARGET_SIDE_TRIANGLES = 9000

SOURCE_FILES = {
    "obj": "54d7ed78b389e2f7fba92288f136b80c.obj",
    "mtl": "material.mtl",
    "albedo": "texture_pbr_20250901.png",
    "metallic": "texture_pbr_20250901_metallic.png",
    "normal": "texture_pbr_20250901_normal.png",
    "roughness": "texture_pbr_20250901_roughness.png",
}

OUTPUT_FILES = (
    "hands_model.js",
    "hands_tex.js",
    "hands_albedo.webp",
    "hands_normal.webp",
    "hands_mr.webp",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def resolve_index(raw_index: int, count: int) -> int:
    index = raw_index - 1 if raw_index > 0 else count + raw_index
    if index < 0 or index >= count:
        raise ValueError(f"OBJ index {raw_index} is outside a list of {count} entries")
    return index


def parse_obj(path: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Read OBJ positions, UVs and triangle corner indices without a loader."""

    positions: list[tuple[float, float, float]] = []
    texcoords: list[tuple[float, float]] = []
    position_faces: list[tuple[int, int, int]] = []
    uv_faces: list[tuple[int, int, int]] = []

    with path.open("r", encoding="utf-8", errors="strict") as stream:
        for line_number, raw_line in enumerate(stream, start=1):
            fields = raw_line.strip().split()
            if not fields or fields[0].startswith("#"):
                continue
            if fields[0] == "v":
                if len(fields) < 4:
                    raise ValueError(f"OBJ line {line_number} has an incomplete position")
                positions.append(tuple(float(value) for value in fields[1:4]))
                continue
            if fields[0] == "vt":
                if len(fields) < 3:
                    raise ValueError(f"OBJ line {line_number} has an incomplete UV")
                texcoords.append(tuple(float(value) for value in fields[1:3]))
                continue
            if fields[0] != "f":
                continue
            if len(fields) < 4:
                raise ValueError(f"OBJ line {line_number} has fewer than three corners")

            polygon_positions: list[int] = []
            polygon_uvs: list[int] = []
            for corner in fields[1:]:
                parts = corner.split("/")
                if len(parts) < 2 or not parts[0] or not parts[1]:
                    raise ValueError(f"OBJ line {line_number} is missing a position/UV pair")
                polygon_positions.append(resolve_index(int(parts[0]), len(positions)))
                polygon_uvs.append(resolve_index(int(parts[1]), len(texcoords)))
            for corner_index in range(1, len(polygon_positions) - 1):
                position_faces.append((polygon_positions[0], polygon_positions[corner_index], polygon_positions[corner_index + 1]))
                uv_faces.append((polygon_uvs[0], polygon_uvs[corner_index], polygon_uvs[corner_index + 1]))

    if not positions or not texcoords or not position_faces:
        raise ValueError(f"OBJ has no complete position/UV triangles: {path}")
    if len(position_faces) != len(uv_faces):
        raise AssertionError("Position and UV triangle counts diverged")
    return (
        np.asarray(positions, dtype=np.float64),
        np.asarray(texcoords, dtype=np.float64),
        np.asarray(position_faces, dtype=np.int64),
        np.asarray(uv_faces, dtype=np.int64),
    )


class DisjointSet:
    def __init__(self, count: int) -> None:
        self.parent = np.arange(count, dtype=np.int64)

    def find(self, value: int) -> int:
        root = value
        while self.parent[root] != root:
            root = int(self.parent[root])
        while self.parent[value] != value:
            next_value = int(self.parent[value])
            self.parent[value] = root
            value = next_value
        return root

    def union(self, first: int, second: int) -> None:
        first_root = self.find(first)
        second_root = self.find(second)
        if first_root != second_root:
            self.parent[second_root] = first_root


def build_side_mesh(
    positions: np.ndarray,
    texcoords: np.ndarray,
    position_faces: np.ndarray,
    uv_faces: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, dict]:
    """Create one side and duplicate only vertices that bridge UV islands."""

    triangle_count = len(position_faces)
    if triangle_count == 0:
        raise ValueError("A hand component has no faces")

    # UV islands meet through an edge only when both endpoint position/UV
    # pairs match.  Keeping the island id in the later clustering key prevents
    # a simplifier cell from welding two different atlas islands.
    pair_keys = [
        tuple((int(position_faces[index, corner]), int(uv_faces[index, corner])) for corner in range(3))
        for index in range(triangle_count)
    ]
    sets = DisjointSet(triangle_count)
    edge_owner: dict[tuple[tuple[int, int], tuple[int, int]], int] = {}
    for triangle_index, corners in enumerate(pair_keys):
        for edge_index in range(3):
            first = corners[edge_index]
            second = corners[(edge_index + 1) % 3]
            edge = (first, second) if first <= second else (second, first)
            previous = edge_owner.get(edge)
            if previous is None:
                edge_owner[edge] = triangle_index
            else:
                sets.union(previous, triangle_index)

    roots = [sets.find(index) for index in range(triangle_count)]
    root_to_chart: dict[int, int] = {}
    triangle_charts: list[int] = []
    for root in roots:
        if root not in root_to_chart:
            root_to_chart[root] = len(root_to_chart)
        triangle_charts.append(root_to_chart[root])

    local_index: dict[tuple[int, int, int], int] = {}
    local_positions: list[tuple[float, float, float]] = []
    local_uvs: list[tuple[float, float]] = []
    local_faces: list[tuple[int, int, int]] = []
    for triangle_index, corners in enumerate(pair_keys):
        chart = triangle_charts[triangle_index]
        local_face: list[int] = []
        for position_index, uv_index in corners:
            key = (position_index, uv_index, chart)
            output_index = local_index.get(key)
            if output_index is None:
                output_index = len(local_positions)
                local_index[key] = output_index
                local_positions.append(tuple(float(value) for value in positions[position_index]))
                local_uvs.append(tuple(float(value) for value in texcoords[uv_index]))
            local_face.append(output_index)
        local_faces.append(tuple(local_face))

    local_positions_array = np.asarray(local_positions, dtype=np.float64)
    local_uvs_array = np.asarray(local_uvs, dtype=np.float64)
    local_faces_array = np.asarray(local_faces, dtype=np.int64)
    local_chart_ids = np.empty(len(local_positions), dtype=np.int64)
    for key, output_index in local_index.items():
        local_chart_ids[output_index] = key[2]
    return local_positions_array, local_uvs_array, local_faces_array, {
        "chartCount": len(root_to_chart),
        "chartIds": local_chart_ids,
    }


def normalize_hand(vertices: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Put the wrist end at local Y=0 and center the hand on local X/Z."""

    source_minimum = vertices.min(axis=0)
    source_maximum = vertices.max(axis=0)
    origin = np.asarray(
        [
            (source_minimum[0] + source_maximum[0]) * 0.5,
            source_maximum[1],
            (source_minimum[2] + source_maximum[2]) * 0.5,
        ],
        dtype=np.float64,
    )
    normalized = vertices - origin
    return normalized, source_minimum, source_maximum


def compact_mesh(
    vertices: np.ndarray,
    uvs: np.ndarray,
    faces: np.ndarray,
    chart_ids: np.ndarray | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray | None]:
    if len(faces) == 0:
        return vertices[:0], uvs[:0], faces.reshape(0, 3), None if chart_ids is None else chart_ids[:0]
    used = np.unique(faces.reshape(-1))
    remap = np.full(len(vertices), -1, dtype=np.int64)
    remap[used] = np.arange(len(used), dtype=np.int64)
    return (
        vertices[used],
        uvs[used],
        remap[faces],
        None if chart_ids is None else chart_ids[used],
    )


def cluster_mesh(
    vertices: np.ndarray,
    uvs: np.ndarray,
    faces: np.ndarray,
    chart_ids: np.ndarray,
    cell_size: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    if cell_size <= 1e-12:
        return vertices.copy(), uvs.copy(), faces.copy(), chart_ids.copy()

    position_minimum = vertices.min(axis=0)
    uv_minimum = uvs.min(axis=0)
    position_cells = np.floor((vertices - position_minimum) / cell_size + 1e-10).astype(np.int64)
    # A relative UV cell keeps atlas detail proportional to the spatial cell.
    # The chart id is still part of the key, so seams can never be welded.
    extent = max(float(np.max(vertices.max(axis=0) - position_minimum)), 1e-9)
    uv_cell_size = max(1.0 / 8192.0, cell_size / extent * 0.95)
    uv_cells = np.floor((uvs - uv_minimum) / uv_cell_size + 1e-10).astype(np.int64)
    keys = np.column_stack((chart_ids, position_cells, uv_cells))
    _, inverse = np.unique(keys, axis=0, return_inverse=True)
    cluster_count = int(inverse.max()) + 1

    summed_positions = np.zeros((cluster_count, 3), dtype=np.float64)
    summed_uvs = np.zeros((cluster_count, 2), dtype=np.float64)
    counts = np.bincount(inverse, minlength=cluster_count).astype(np.float64)
    np.add.at(summed_positions, inverse, vertices)
    np.add.at(summed_uvs, inverse, uvs)
    output_vertices = summed_positions / counts[:, None]
    output_uvs = summed_uvs / counts[:, None]
    output_chart_ids = np.zeros(cluster_count, dtype=np.int64)
    np.maximum.at(output_chart_ids, inverse, chart_ids)
    output_faces = inverse[faces]

    valid = (
        (output_faces[:, 0] != output_faces[:, 1])
        & (output_faces[:, 1] != output_faces[:, 2])
        & (output_faces[:, 0] != output_faces[:, 2])
    )
    output_faces = output_faces[valid]
    if len(output_faces):
        canonical = np.sort(output_faces, axis=1)
        _, unique_indices = np.unique(canonical, axis=0, return_index=True)
        output_faces = output_faces[np.sort(unique_indices)]
    return compact_mesh(output_vertices, output_uvs, output_faces, output_chart_ids)


def simplify_to_target(
    vertices: np.ndarray,
    uvs: np.ndarray,
    faces: np.ndarray,
    chart_ids: np.ndarray,
    target_triangles: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float]:
    if len(faces) <= target_triangles:
        return vertices.copy(), uvs.copy(), faces.copy(), chart_ids.copy(), 0.0

    extent = float(np.max(vertices.max(axis=0) - vertices.min(axis=0)))
    low = 0.0
    high = max(extent / 16.0, 1e-6)
    best: tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float] | None = None
    while True:
        candidate = cluster_mesh(vertices, uvs, faces, chart_ids, high)
        if len(candidate[2]) <= target_triangles:
            best = (*candidate, high)
            break
        high *= 1.5
        if high > extent * 2.0:
            raise RuntimeError("UV-aware simplifier could not reach its triangle target")

    # The count is not strictly monotonic around isolated grid boundaries, so
    # retain the densest candidate at or below the target seen during search.
    for _ in range(28):
        middle = (low + high) * 0.5
        candidate = cluster_mesh(vertices, uvs, faces, chart_ids, middle)
        if len(candidate[2]) > target_triangles:
            low = middle
        else:
            high = middle
            if best is None or len(candidate[2]) > len(best[2]):
                best = (*candidate, middle)
    if best is None:
        raise AssertionError("simplifier returned no candidate")
    return best


def compute_vertex_normals(vertices: np.ndarray, faces: np.ndarray) -> np.ndarray:
    normals = np.zeros_like(vertices, dtype=np.float64)
    triangle_normals = np.cross(
        vertices[faces[:, 1]] - vertices[faces[:, 0]],
        vertices[faces[:, 2]] - vertices[faces[:, 0]],
    )
    for corner in range(3):
        np.add.at(normals, faces[:, corner], triangle_normals)
    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    if np.any(lengths <= 1e-12):
        raise RuntimeError("Simplified mesh contains a vertex without a valid normal")
    return normals / lengths


def encode_u16(values: np.ndarray) -> str:
    return base64.b64encode(np.asarray(values, dtype="<u2").tobytes(order="C")).decode("ascii")


def encode_snorm8(values: np.ndarray) -> str:
    return base64.b64encode(np.asarray(values, dtype=np.int8).tobytes(order="C")).decode("ascii")


def quantize_positions(vertices: np.ndarray) -> tuple[np.ndarray, dict, float]:
    minimum = vertices.min(axis=0)
    maximum = vertices.max(axis=0)
    scale = (maximum - minimum) / 65535.0
    scale[scale <= 0.0] = 1.0
    packed = np.rint((vertices - minimum) / scale).clip(0.0, 65535.0).astype(np.uint16)
    decoded = minimum + packed.astype(np.float64) * scale
    error = float(np.max(np.abs(decoded - vertices)))
    return packed, {
        "encoding": "uint16",
        "min": [float(value) for value in minimum],
        "scale": [float(value) for value in scale],
        "maxError": error,
    }, error


def quantize_uvs(uvs: np.ndarray) -> tuple[np.ndarray, dict, float]:
    minimum = uvs.min(axis=0)
    maximum = uvs.max(axis=0)
    scale = (maximum - minimum) / 65535.0
    scale[scale <= 0.0] = 1.0
    packed = np.rint((uvs - minimum) / scale).clip(0.0, 65535.0).astype(np.uint16)
    decoded = minimum + packed.astype(np.float64) * scale
    error = float(np.max(np.abs(decoded - uvs)))
    return packed, {
        "encoding": "uint16",
        "min": [float(value) for value in minimum],
        "scale": [float(value) for value in scale],
        "maxError": error,
    }, error


def quantize_normals(normals: np.ndarray) -> tuple[np.ndarray, dict, float]:
    packed = np.rint(np.clip(normals, -1.0, 1.0) * 127.0).clip(-127.0, 127.0).astype(np.int8)
    decoded = packed.astype(np.float64) / 127.0
    decoded /= np.maximum(np.linalg.norm(decoded, axis=1, keepdims=True), 1e-12)
    dots = np.sum(normals * decoded, axis=1).clip(-1.0, 1.0)
    angle_error = float(np.degrees(np.arccos(dots)).max())
    return packed, {
        "encoding": "int8-snorm",
        "decode": "normalize(int8 / 127)",
        "maxAngleErrorDegrees": angle_error,
    }, angle_error


def round_bounds(values: np.ndarray) -> list[float]:
    return [float(value) for value in values]


def make_side_payload(
    handedness: str,
    normalized_source_vertices: np.ndarray,
    source_uvs: np.ndarray,
    source_faces: np.ndarray,
    chart_ids: np.ndarray,
    source_bounds: tuple[np.ndarray, np.ndarray],
    origin: np.ndarray,
) -> tuple[dict, dict]:
    simplified_vertices, simplified_uvs, simplified_faces, simplified_charts, cell_size = simplify_to_target(
        normalized_source_vertices,
        source_uvs,
        source_faces,
        chart_ids,
        TARGET_SIDE_TRIANGLES,
    )
    normals = compute_vertex_normals(simplified_vertices, simplified_faces)
    packed_positions, position_meta, position_error = quantize_positions(simplified_vertices)
    packed_uvs, uv_meta, _ = quantize_uvs(simplified_uvs)
    packed_normals, normal_meta, normal_error = quantize_normals(normals)
    if position_error > 0.00002 + 1e-12:
        raise RuntimeError(f"{handedness} position quantization error exceeds 0.00002: {position_error}")
    if normal_error > 1.0 + 1e-9:
        raise RuntimeError(f"{handedness} normal quantization error exceeds 1 degree: {normal_error}")
    if len(simplified_vertices) > 65535:
        raise RuntimeError(f"{handedness} has too many vertices for Uint16 indices")

    payload = {
        "handedness": handedness,
        "vertexCount": int(len(simplified_vertices)),
        "triangleCount": int(len(simplified_faces)),
        "positionMin": position_meta["min"],
        "positionScale": position_meta["scale"],
        "uvMin": uv_meta["min"],
        "uvScale": uv_meta["scale"],
        "position": encode_u16(packed_positions.reshape(-1)),
        "uv": encode_u16(packed_uvs.reshape(-1)),
        "normal": encode_snorm8(packed_normals.reshape(-1)),
        "index": encode_u16(simplified_faces.reshape(-1)),
    }
    source_minimum, source_maximum = source_bounds
    output_minimum = simplified_vertices.min(axis=0)
    output_maximum = simplified_vertices.max(axis=0)
    metadata = {
        "handedness": handedness,
        "sourceTriangleCount": int(len(source_faces)),
        "sourceVertexCount": int(len(normalized_source_vertices)),
        "sourceChartCount": int(np.max(chart_ids) + 1),
        "outputTriangleCount": int(len(simplified_faces)),
        "outputVertexCount": int(len(simplified_vertices)),
        "simplification": {
            "method": "deterministic-uv-aware-vertex-cluster",
            "cellSize": float(cell_size),
            "targetTriangles": TARGET_SIDE_TRIANGLES,
            "sourceTriangles": int(len(source_faces)),
        },
        "sourceBounds": {"min": round_bounds(source_minimum), "max": round_bounds(source_maximum)},
        "normalizedBounds": {
            "min": round_bounds(normalized_source_vertices.min(axis=0)),
            "max": round_bounds(normalized_source_vertices.max(axis=0)),
        },
        "outputBounds": {"min": round_bounds(output_minimum), "max": round_bounds(output_maximum)},
        "wristOrigin": round_bounds(origin),
        "quantization": {
            "position": position_meta,
            "uv": uv_meta,
            "normal": normal_meta,
            "index": "uint16",
        },
        "componentEvidence": {
            "axis": "x",
            "sign": "positive" if handedness == "right" else "negative",
            "allCornersSameSign": True,
            "sourceTriangleCount": int(len(source_faces)),
        },
    }
    return payload, metadata


def build_mesh_payload(
    positions: np.ndarray,
    texcoords: np.ndarray,
    position_faces: np.ndarray,
    uv_faces: np.ndarray,
) -> tuple[dict[str, dict], dict[str, dict], dict]:
    components = {
        "right": np.all(positions[position_faces, 0] > 0.0, axis=1),
        "left": np.all(positions[position_faces, 0] < 0.0, axis=1),
    }
    if np.any(~(components["right"] | components["left"])):
        raise RuntimeError("OBJ contains a face crossing the X=0 hand split")
    if int(components["right"].sum()) != 25064 or int(components["left"].sum()) != 24906:
        raise RuntimeError("Archived hand component face counts changed; refusing an unsafe split")

    payloads: dict[str, dict] = {}
    metadata: dict[str, dict] = {}
    evidence: dict[str, dict] = {}
    for handedness in ("left", "right"):
        mask = components[handedness]
        side_positions, side_uvs, side_faces, side_info = build_side_mesh(
            positions,
            texcoords,
            position_faces[mask],
            uv_faces[mask],
        )
        normalized, source_minimum, source_maximum = normalize_hand(side_positions)
        origin = np.asarray(
            [
                (source_minimum[0] + source_maximum[0]) * 0.5,
                source_maximum[1],
                (source_minimum[2] + source_maximum[2]) * 0.5,
            ],
            dtype=np.float64,
        )
        payload, side_metadata = make_side_payload(
            handedness,
            normalized,
            side_uvs,
            side_faces,
            side_info["chartIds"],
            (source_minimum, source_maximum),
            origin,
        )
        payloads[handedness] = payload
        metadata[handedness] = side_metadata
        evidence[handedness] = {
            "axis": "x",
            "sign": "positive" if handedness == "right" else "negative",
            "faceCount": int(mask.sum()),
            "positionCount": int(np.unique(position_faces[mask]).size),
            "allFacesContained": True,
            "crossComponentFaces": 0,
        }
    total_triangles = sum(item["triangleCount"] for item in payloads.values())
    if total_triangles > TARGET_TOTAL_TRIANGLES:
        raise RuntimeError(f"Simplified hand payload has {total_triangles} triangles")
    return payloads, metadata, {
        "axis": "x",
        "componentCount": 2,
        "right": evidence["right"],
        "left": evidence["left"],
        "crossComponentFaces": 0,
    }


def save_webp(image: Image.Image, path: Path, size: int, quality: int) -> None:
    resized = image.resize((size, size), Image.Resampling.LANCZOS)
    resized.save(path, "WEBP", quality=quality, method=6, exact=True)


def build_textures(source: Path, output: Path) -> dict[str, dict]:
    albedo_path = output / "hands_albedo.webp"
    normal_path = output / "hands_normal.webp"
    mr_path = output / "hands_mr.webp"

    with Image.open(source / SOURCE_FILES["albedo"]) as image:
        save_webp(image.convert("RGB"), albedo_path, 1024, 86)

    with Image.open(source / SOURCE_FILES["normal"]) as image:
        normal = image.convert("RGB").resize((1024, 1024), Image.Resampling.LANCZOS)
    normal_array = np.asarray(normal, dtype=np.float32) / 127.5 - 1.0
    normal_length = np.linalg.norm(normal_array, axis=2, keepdims=True)
    normal_array /= np.maximum(normal_length, 1e-6)
    normal_encoded = np.rint((normal_array + 1.0) * 127.5).clip(0.0, 255.0).astype(np.uint8)
    Image.fromarray(normal_encoded, "RGB").save(normal_path, "WEBP", quality=90, method=6, exact=True)

    with Image.open(source / SOURCE_FILES["metallic"]) as image:
        metallic = image.convert("L").resize((512, 512), Image.Resampling.LANCZOS)
    with Image.open(source / SOURCE_FILES["roughness"]) as image:
        roughness = image.convert("L").resize((512, 512), Image.Resampling.LANCZOS)
    mr = np.empty((512, 512, 3), dtype=np.uint8)
    mr[:, :, 0] = 255
    mr[:, :, 1] = np.asarray(roughness, dtype=np.uint8)
    mr[:, :, 2] = np.asarray(metallic, dtype=np.uint8)
    # MR is data, not color imagery: lossless WebP keeps the constant R=255
    # channel exact after the browser decodes it.
    Image.fromarray(mr, "RGB").save(mr_path, "WEBP", lossless=True, method=6, exact=True)

    records = {
        path.name: {
            "bytes": path.stat().st_size,
            "sha256": sha256(path),
            "dimensions": [1024, 1024] if path != mr_path else [512, 512],
            "format": "WEBP",
        }
        for path in (albedo_path, normal_path, mr_path)
    }
    records[albedo_path.name]["colorSpace"] = "sRGB"
    records[normal_path.name]["colorSpace"] = "none; tangent-space normal"
    records[mr_path.name]["colorSpace"] = "none"
    records[mr_path.name]["channels"] = {"r": "255", "g": "roughness", "b": "metallic"}
    return records


def write_model_js(path: Path, payloads: dict[str, dict], source_hash: str, metadata: dict[str, dict]) -> None:
    runtime_metadata = {
        "version": 1,
        "sourceHash": source_hash,
        "quantized": True,
        "hands": {
            handedness: {
                "triangleCount": metadata[handedness]["outputTriangleCount"],
                "vertexCount": metadata[handedness]["outputVertexCount"],
            }
            for handedness in ("left", "right")
        },
    }
    data = json.dumps({"hands": payloads}, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    metadata_json = json.dumps(runtime_metadata, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    content = f"""// Generated by tools/build-hand-assets.py; do not hand-edit.
(function (global) {{
  'use strict';
  var DATA = {data};
  function freeze(value) {{
    if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
    Object.freeze(value);
    Object.keys(value).forEach(function (key) {{ freeze(value[key]); }});
    return value;
  }}
  var META = freeze({metadata_json});
  var geometryCache = {{ left: null, right: null }};

  function decodedBytes(encoded) {{
    var binary = atob(encoded);
    var result = new Uint8Array(binary.length);
    for (var i = 0; i < binary.length; i++) result[i] = binary.charCodeAt(i);
    return result;
  }}

  function decodedU16(encoded, itemSize, minimum, scale) {{
    var raw = decodedBytes(encoded);
    var packed = new Uint16Array(raw.buffer);
    var result = new Float32Array(packed.length);
    for (var i = 0; i < packed.length; i++) result[i] = minimum[i % itemSize] + packed[i] * scale[i % itemSize];
    return result;
  }}

  function decodedNormals(encoded) {{
    var raw = decodedBytes(encoded);
    var packed = new Int8Array(raw.buffer);
    var result = new Float32Array(packed.length);
    for (var i = 0; i < packed.length; i += 3) {{
      var x = packed[i] / 127;
      var y = packed[i + 1] / 127;
      var z = packed[i + 2] / 127;
      var length = Math.hypot(x, y, z) || 1;
      result[i] = x / length;
      result[i + 1] = y / length;
      result[i + 2] = z / length;
    }}
    return result;
  }}

  function three() {{
    var library = global.THREE;
    if (!library && typeof THREE !== 'undefined') library = THREE;
    if (!library) throw new Error('HandsModel requires THREE');
    return library;
  }}

  function makeGeometry(handedness) {{
    if (geometryCache[handedness]) return geometryCache[handedness];
    var library = three();
    var item = DATA.hands[handedness];
    var geometry = new library.BufferGeometry();
    geometry.setAttribute('position', new library.BufferAttribute(decodedU16(item.position, 3, item.positionMin, item.positionScale), 3));
    geometry.setAttribute('normal', new library.BufferAttribute(decodedNormals(item.normal), 3));
    geometry.setAttribute('uv', new library.BufferAttribute(decodedU16(item.uv, 2, item.uvMin, item.uvScale), 2));
    geometry.setIndex(new library.BufferAttribute(new Uint16Array(decodedBytes(item.index).buffer), 1));
    geometry.computeBoundingSphere();
    geometryCache[handedness] = geometry;
    return geometry;
  }}

  function build(handedness, material) {{
    if (handedness !== 'left' && handedness !== 'right') throw new Error('Unknown hand: ' + handedness);
    var library = three();
    var mesh = new library.Mesh(makeGeometry(handedness), material);
    mesh.name = 'hand-' + handedness;
    mesh.userData = mesh.userData || {{}};
    mesh.userData.handedness = handedness;
    return mesh;
  }}

  function buildPair(material) {{
    var library = three();
    var group = new library.Group();
    group.name = 'hands-pair';
    var left = build('left', material);
    var right = build('right', material);
    group.add(left);
    group.add(right);
    group.userData = group.userData || {{}};
    group.userData.leftHand = left;
    group.userData.rightHand = right;
    return group;
  }}

  var api = freeze({{ build: build, buildPair: buildPair, metadata: META }});
  if (typeof window !== 'undefined') {{
    Object.defineProperty(window, 'HandsModel', {{ value: api, enumerable: true, writable: false, configurable: false }});
  }} else {{
    Object.defineProperty(global, 'HandsModel', {{ value: api, enumerable: true, writable: false, configurable: false }});
  }}
}})(typeof window !== 'undefined' ? window : this);
"""
    path.write_text(content, encoding="utf-8", newline="\n")


def write_texture_js(path: Path) -> None:
    content = """// Package-local first-person hand PBR texture paths.
window.HandsTex = {
  albedo: 'hands_albedo.webp',
  normal: 'hands_normal.webp',
  mr: 'hands_mr.webp',
  metallic: 'hands_mr.webp',
  roughness: 'hands_mr.webp',
  albedoSize: 1024,
  normalSize: 1024,
  mrSize: 512,
  mime: 'image/webp'
};

let handsAlbedoPromise = null;
let handsLoadAllPromise = null;

function loadHandsTexture(loader, path, colorSpace) {
  return new Promise((resolve) => {
    loader.load(
      path,
      (texture) => {
        texture.userData = texture.userData || {};
        texture.userData.cs15PersistentAsset = true;
        texture.wrapS = texture.wrapT = THREE.ClampToEdgeWrapping;
        texture.colorSpace = colorSpace;
        texture.needsUpdate = true;
        resolve(texture);
      },
      undefined,
      () => resolve(null)
    );
  });
}

function loadHandsAlbedo(loader) {
  if (!handsAlbedoPromise) handsAlbedoPromise = loadHandsTexture(loader, window.HandsTex.albedo, THREE.SRGBColorSpace);
  return handsAlbedoPromise;
}

window.HandsTex.loadAll = function (options) {
  const lowEnd = !!(options && options.lowEnd);
  if (lowEnd) {
    const loader = new THREE.TextureLoader();
    return loadHandsAlbedo(loader).then((albedo) => ({
      albedo,
      normal: null,
      metallic: null,
      roughness: null,
      mr: null
    }));
  }
  if (handsLoadAllPromise) return handsLoadAllPromise;

  const loader = new THREE.TextureLoader();
  handsLoadAllPromise = Promise.all([
    loadHandsAlbedo(loader),
    loadHandsTexture(loader, window.HandsTex.normal, THREE.NoColorSpace),
    loadHandsTexture(loader, window.HandsTex.mr, THREE.NoColorSpace)
  ]).then(([albedo, normal, mr]) => ({
    albedo,
    normal,
    metallic: mr,
    roughness: mr,
    mr
  }));

  return handsLoadAllPromise;
};
"""
    path.write_text(content, encoding="utf-8", newline="\n")


def output_record(path: Path, root: Path) -> dict:
    return {
        "path": str(path.relative_to(root)).replace("\\", "/"),
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=None, help="archived source directory")
    parser.add_argument("--output", type=Path, default=None, help="project root for generated assets")
    args = parser.parse_args()

    output = (args.output or Path(__file__).resolve().parents[1]).resolve()
    source = (args.source or output / "archive" / "assets" / "hands" / "source-20260829").resolve()
    for filename in SOURCE_FILES.values():
        if not (source / filename).is_file():
            raise FileNotFoundError(source / filename)

    obj_hash = sha256(source / SOURCE_FILES["obj"])
    if obj_hash != EXPECTED_OBJ_SHA256:
        raise RuntimeError(f"Archived hand OBJ hash mismatch: expected {EXPECTED_OBJ_SHA256}, got {obj_hash}")

    positions, texcoords, position_faces, uv_faces = parse_obj(source / SOURCE_FILES["obj"])
    payloads, side_metadata, component_evidence = build_mesh_payload(
        positions,
        texcoords,
        position_faces,
        uv_faces,
    )
    output.mkdir(parents=True, exist_ok=True)
    write_model_js(output / "hands_model.js", payloads, obj_hash, side_metadata)
    write_texture_js(output / "hands_tex.js")
    texture_records = build_textures(source, output)

    model_record = output_record(output / "hands_model.js", output)
    texture_js_record = output_record(output / "hands_tex.js", output)
    records = {
        model_record["path"]: model_record,
        texture_js_record["path"]: texture_js_record,
    }
    for filename, record in texture_records.items():
        records[filename] = {
            "path": filename,
            "bytes": record["bytes"],
            "sha256": record["sha256"],
        }

    source_hashes = {key: sha256(source / filename) for key, filename in SOURCE_FILES.items()}
    manifest = {
        "version": 1,
        "pipeline": "hands-obj-quantized-rigid-v1",
        "sourceDirectory": "archive/assets/hands/source-20260829",
        "sourceHash": obj_hash,
        "sourceHashes": source_hashes,
        "sourceStats": {
            "positions": int(len(positions)),
            "uvs": int(len(texcoords)),
            "triangles": int(len(position_faces)),
            "normals": 0,
            "materials": 1,
        },
        "componentEvidence": component_evidence,
        "normalization": {
            "wristAxis": "source-y-max",
            "localOrigin": "wrist-end at Y=0; X/Z centered by component bounds",
            "preserveSourceWinding": True,
        },
        "buildParameters": {
            "targetTotalTriangles": TARGET_TOTAL_TRIANGLES,
            "targetTrianglesPerHand": TARGET_SIDE_TRIANGLES,
            "simplifier": "deterministic-uv-aware-vertex-cluster",
            "positionEncoding": "uint16",
            "uvEncoding": "uint16",
            "normalEncoding": "int8-snorm",
            "indexEncoding": "uint16",
            "positionErrorLimit": 0.00002,
            "normalAngleErrorLimitDegrees": 1.0,
            "textureQuality": {"albedo": 86, "normal": 90, "mr": "lossless"},
        },
        "model": {
            "file": "hands_model.js",
            "triangleCount": sum(item["outputTriangleCount"] for item in side_metadata.values()),
            "vertexCount": sum(item["outputVertexCount"] for item in side_metadata.values()),
            "quantized": True,
            "hands": side_metadata,
        },
        "textures": texture_records,
        "outputs": records,
    }
    docs_path = output / "docs" / "hands-model-build.json"
    docs_path.parent.mkdir(parents=True, exist_ok=True)
    docs_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
